CREATE USER 'amc'@'localhost' IDENTIFIED BY '';
CREATE DATABASE amc;
USE amc;
CREATE TABLE emails ( id BIGINT NOT NULL AUTO_INCREMENT, path VARCHAR(512) NOT NULL, PRIMARY KEY (id) );
CREATE UNIQUE INDEX i_emails_path ON emails(path);
GRANT SELECT, INSERT, UPDATE, DELETE ON amc.* TO 'amc'@'localhost';
FLUSH PRIVILEGES;
